### ISSUE TITLE
カラーテーマを設定したい

### ISSUE THREAD

**Issue by 7vk1** [sugarnaoming/chachamaru-android#13]
もっとこう明るい配色にしたいなぁとか、タブの色をつけたいなぁとかあるんじゃないかなと。

**Comment by sugarnaoming** [comment]
内容をアプリケーションの全体配色とタブ個別の色設定の2つに分割して再度Issueを立てたのでこちらを閉じたいと思います。
アプリケーション全体の配色変更: #14 
タブに対して個別に色を設定する: #15
